package com.uyscuti.social.network.api.response.latestFeedPostsExample

data class OriginalPost(
    val __v: Int,
    val _id: String,
    val author: String,
    val bookmarkCount: Int,
    val commentCount: Int,
    val content: String,
    val contentType: String,
    val createdAt: String,
    val duration: List<Duration>,
    val feedShortsBusinessId: String,
    val fileIds: List<String>,
    val fileNames: List<FileName>,
    val fileSizes: List<FileSize>,
    val fileTypes: List<FileType>,
    val files: List<File>,
    val isReposted: Boolean,
    val likeCount: Int,
    val numberOfPages: List<NumberOfPage>,
    val originalAuthor: OriginalAuthor,
    val originalPostId: String,
    val repostCount: Int,
    val repostedByUserId: String,
    val repostedUser: RepostedUserX,
    val repostedUsers: List<String>,
    val tags: List<Any?>,
    val thumbnail: List<ThumbnailX>,
    val updatedAt: String
)