package com.uyscuti.social.network.api.response.exampletrial

data class Post(
    val __v: Int,
    val _id: String,
    val bookmarkCount: Int,
    val comments: List<Comment>,
    val content: String,
    val contentType: String,
    val createdAt: String,
    val duration: List<Duration>,
    val feedShortsBusinessId: String,
    val fileIds: List<String>,
    val fileNames: List<FileName>,
    val fileSizes: List<FileSize>,
    val fileTypes: List<FileType>,
    val files: List<File>,
    val isBookmarked: Boolean,
    val isExpanded: Boolean,
    val isLiked: Boolean,
    val isLocal: Boolean,
    val isReposted: Boolean,
    val likes: Int,
    val numberOfPages: List<NumberOfPage>,
    val originalPost: List<OriginalPost>,
    val repostedByUserId: String,
    val repostedUser: RepostedUser,
    val repostedUsers: List<String>,
    val tags: List<Any?>,
    val thumbnail: List<Thumbnail>,
    val updatedAt: String
)